```
# export GOPATH=$HOME/go
# export PATH=$PATH:$GOPATH/bin
. ~/opt/z/z.sh

# export GO111MODULE=on
eval $(ssh-agent -s)
ssh-add ~/.ssh/gitlab

export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'
```
